const tags = [
    {tag_id: 1, name: 'JavaScript', favourite: true, color: `#FF0000`},
    {tag_id: 2, name: 'Workshop', favourite: false}, 
    {tag_id: 3,name: 'Conference', favourite: false, color: `#F4D03F`}, 
    {tag_id: 4,name: 'gbc', favourite: false},
    {tag_id: 5,name: 'Semester 2', favourite: false, color: `#3498DB`}, 
    {tag_id: 6, name: 'html', favourite: true}, 
    {tag_id: 7,name: 'css', favourite: true},
    {tag_id: 8, name: 'Photoshop', favourite: false}, 
    {tag_id: 9,name: 'Javascript', favourite: false}, 
    {tag_id: 10, name: 'School Information', favourite: true, color: `#FF0000`}, 
    {tag_id: 11, name: 'Illustrator', favourite: false},
    {tag_id: 12, name: 'Theory Embalming', favourite: false, color: `#28B463`}, 
    {tag_id: 13, name: 'Embalming Practical', favourite: false}, 
    {tag_id: 14, name: 'Illustrator', favourite: true},
],